Models/Vendor.cs
namespace VoucherApp.Models
{
    public class Vendor 
    {
        public int Id { get; set; }
        public string UserEmail { get; set; }
        public string Name { get; set; }
        public string DessertType { get; set; }
        public string ImagePath { get; set; }
        public string StripeAccountId { get; set; }
        public string StripeState { get; set; }
        public string Description { get; set; }
        public string SocialMediaLink { get; set; }
    }
}

Controllers/VendorController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using VoucherApp.Data;

namespace VoucherApp.Controllers
{
    [Authorize]
    [Route("[controller]/[action]")]
    public class VendorController : Controller
    {
        private readonly DataContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public VendorController(DataContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [HttpPost]
        public async Task<IActionResult> Remove(int id)
        {
            var vendor = await _context.Vendors.FindAsync(id);
            var user = await _userManager.FindByEmailAsync(vendor.UserEmail);

            await _userManager.DeleteAsync(user);

            _context.Vendors.Remove(vendor);
            await _context.SaveChangesAsync();

            return Redirect("~/Admin/Vendors");
        }
    }
}

Pages/Accounts/Edit.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace VoucherApp.Pages.Accounts
{
    public class EditModel : PageModel
    {
        private readonly UserManager<IdentityUser> _userManager;

        public EditModel(UserManager<IdentityUser> userManager)
        {
            _userManager = userManager;
        }

        [BindProperty]
        public InputModel Input { get; set; }
        public bool Success { get; set; }

        public class InputModel
        {
            [Required]
            [DataType(DataType.Password)]
            [Display(Name = "Old Password")]
            public string OldPassword { get; set; }

            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }
        }

        public IActionResult OnGet()
        {
            Success = false;

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            var userEmail = User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Email).Value;
            if (ModelState.IsValid && userEmail != null)
            {
                var currentUser = await _userManager.FindByEmailAsync(userEmail);
                var updateResult = await _userManager.ChangePasswordAsync(currentUser, Input.OldPassword, Input.Password);
                if (!updateResult.Succeeded)
                {
                    foreach(var error in updateResult.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }

                Success = updateResult.Succeeded;
            }

            return Page();
        }
    }
}

Pages/Admin/Vendors/Details.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using VoucherApp.Data;

namespace VoucherApp.Pages.Admin.Vendors
{
    public class DetailsModel : PageModel
    {
        private readonly DataContext _context;

        public DetailsModel(DataContext context) 
        {
            _context = context;
        }

        public OutputModel Output { get; set; }

        public class OutputModel
        {
            public int Id { get; set; }
            public string Name { get; set; }
            public string Owner { get; set; }

            [Display(Name = "Treat Type")]
            public string DessertType { get; set; }

            [Display(Name = "Image Path")]
            public string ImagePath { get; set; }

            [Display(Name = "Stripe Account Id")]
            public string StripeAccountId { get; set; }

            public string Description { get; set; }

            [Display(Name = "Social Media Link")]
            public string SocialMediaLink { get; set; }
        }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null) 
            {
                return RedirectToPage("/Errors/NotFound");
            }

            var vendor = await _context.Vendors.FirstOrDefaultAsync(m => m.Id == id);

            if (vendor == null)
            {
                return RedirectToPage("/Errors/NotFound");
            }

            Output = new OutputModel
            {
                Id = vendor.Id,
                Name = vendor.Name,
                Owner = vendor.UserEmail,
                DessertType = vendor.DessertType,
                ImagePath = vendor.ImagePath,
                StripeAccountId = vendor.StripeAccountId,
                Description = vendor.Description,
                SocialMediaLink = vendor.SocialMediaLink
            };

            return Page();
        } 
    }
}

Pages/Admin/Vendors/Edit.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using VoucherApp.Data;

namespace VoucherApp.Pages.Admin.Vendors
{
    public class EditModel : PageModel 
    {
        private readonly DataContext _context;

        public EditModel(DataContext context) 
        {
            _context = context;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            public int Id { get; set; }

            [Required]
            public string Name { get; set; }

            [Required]
            [EmailAddress]
            public string Owner { get; set; }

            [Required]
            [Display(Name = "Treat Type")]
            public string DessertType { get; set; }

            [Required]
            [Display(Name = "Place image url")]
            public string ImagePath { get; set; }

            [Display(Name = "Stripe Account Id")]
            public string StripeAccountId { get; set; }

            [Required]
            [StringLength(355)]
            [Display(Name = "Short Description")]
            public string Description { get; set; }

            [Display(Name = "Social Media Link")]
            public string SocialMediaLink { get; set; }
        }

        public async Task<IActionResult> OnGetAsync(int? id) 
        {
            if (id == null) return RedirectToPage("/Errors/NotFound404");

            var vendor = await _context.Vendors.FirstOrDefaultAsync(m => m.Id == id);

            if (vendor == null) return RedirectToPage("/Errors/NotFound404");

            Input = new InputModel { 
                Id = vendor.Id, 
                Owner = vendor.UserEmail,
                Name = vendor.Name, 
                DessertType = vendor.DessertType, 
                StripeAccountId = vendor.StripeAccountId ,
                ImagePath = vendor.ImagePath,
                Description = vendor.Description,
                SocialMediaLink = vendor.SocialMediaLink
            };

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid) return Page();

            var vendor = await _context.Vendors.FirstOrDefaultAsync(m => m.Id == Input.Id);
            vendor.Name = Input.Name;
            vendor.UserEmail = Input.Owner;
            vendor.ImagePath = Input.ImagePath;
            vendor.DessertType = Input.DessertType;
            vendor.StripeAccountId = Input.StripeAccountId;
            vendor.Description = Input.Description;
            vendor.SocialMediaLink = Input.SocialMediaLink;

            _context.Attach(vendor).State = EntityState.Modified;

            try 
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!VendorExists(vendor.Id)) 
                {
                    return RedirectToPage("/Errors/NotFound");
                }
                else 
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool VendorExists(int id)
        {
            return _context.Vendors.Any(e => e.Id == id);
        }
    }
}

Pages/Admin/Vendors/Index.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using VoucherApp.Data;
using VoucherApp.Models;

namespace VoucherApp.Pages.Admin.Vendors
{
    public class IndexModel : PageModel 
    {
        private readonly DataContext _context;

        public IndexModel(DataContext context) 
        {
            _context = context;
        }

        public IList<Vendor> Vendors { get; set; }

        public async Task OnGetAsync() 
        {
            Vendors = await _context.Vendors.ToListAsync();
        }
    }
}

Pages/Vendors/Create.cshtml.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using VoucherApp.Data;
using VoucherApp.Models;

namespace VoucherApp.Pages.Vendors
{
    public class CreateModel : PageModel 
    {
        private readonly DataContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public CreateModel(DataContext context, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager) 
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {
            [Required]
            [Display(Name = "Place Name")]
            public string Name { get; set; }

            [Required]
            [Display(Name = "Treat Type")]
            public string DessertType { get; set; }

            [Required]
            [Display(Name = "Place image url")]
            public string ImageUrl { get; set; }

            [Required]
            [StringLength(355)]
            [Display(Name = "Short Description")]
            public string Description { get; set; }

            [Display(Name = "Social Media Link")]
            public string SocialMediaLink { get; set; }

            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 5)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }
        }

        public IActionResult OnGet() 
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync() 
        {
            if (!ModelState.IsValid) return Page();

            var vendor = new Vendor { 
                Name = Input.Name, 
                DessertType = Input.DessertType, 
                UserEmail = Input.Email , 
                ImagePath = Input.ImageUrl,
                Description = Input.Description,
                SocialMediaLink = Input.SocialMediaLink 
            };
            
            var user = await CreateUserAsync();
            if (user == null)
            {
                ModelState.AddModelError(string.Empty, "User already has a place registered.");
                return Page();
            }

            _context.Vendors.Add(vendor);
            await _context.SaveChangesAsync();

            await LogIn(user);

            return RedirectToPage("./Index");
        }

        private async Task<IdentityUser> CreateUserAsync()
        {
            if (await _userManager.FindByEmailAsync(Input.Email) != null)
            {
                return null;
            }

            var user = new IdentityUser { UserName = Input.Email, Email = Input.Email };
            var result = await _userManager.CreateAsync(user, Input.Password);
            if (result.Succeeded)
            {
                var role = await _roleManager.FindByNameAsync(Roles.User);
                if (role == null) 
                {
                    role = new IdentityRole { Name = Roles.User };
                    await _roleManager.CreateAsync(role);
                }

                await _userManager.AddToRoleAsync(user, role.Name);
            }
            else {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }

                return null;
            }

            return user;
        }

        private async Task LogIn(IdentityUser user) 
        {
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Email, user.Email),
                new Claim(ClaimTypes.Role, (await _userManager.GetRolesAsync(user)).FirstOrDefault())
            };

            var claimsIdentity = new ClaimsIdentity(
                claims, CookieAuthenticationDefaults.AuthenticationScheme);

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme, 
                new ClaimsPrincipal(claimsIdentity));
        }
    }
}

Pages/Admin/Vendors/Details.cshtml
@page "{id:int}"
@model DetailsModel

@{
    ViewData["Title"] = "Details";
    ViewData["SelectedTab"] = "Vendors";
}

<div class="container">
    <h1>@ViewData["Title"]</h1>
    <div>
        <h4>Vendor</h4>
        <hr />
        <dl class="row">
            <dt class="col-lg-4">
                @Html.DisplayNameFor(model => model.Output.Name)
            </dt>
            <dd class="col-lg-8">
                @Html.DisplayFor(model => model.Output.Name)
            </dd>
        </dl>
        <dl class="row">
            <dt class="col-lg-4">
                @Html.DisplayNameFor(model => model.Output.DessertType)
            </dt>
            <dd class="col-lg-8">
                @Html.DisplayFor(model => model.Output.DessertType)
            </dd>
        </dl>
        <dl class="row">
            <dt class="col-lg-4">
                @Html.DisplayNameFor(model => model.Output.Owner)
            </dt>
            <dd class="col-lg-8">
                @Html.DisplayFor(model => model.Output.Owner)
            </dd>
        </dl>
        <dl class="row">
            <dt class="col-lg-4">
                @Html.DisplayNameFor(model => model.Output.ImagePath)
            </dt>
            <dd class="col-lg-8">
                @Html.DisplayFor(model => model.Output.ImagePath)
            </dd>
        </dl>
        <dl class="row">
            <dt class="col-lg-4">
                @Html.DisplayNameFor(model => model.Output.SocialMediaLink)
            </dt>
            <dd class="col-lg-8">
                @Html.DisplayFor(model => model.Output.SocialMediaLink)
            </dd>
        </dl>
        <dl class="row">
            <dt class="col-lg-4">
                @Html.DisplayNameFor(model => model.Output.Description)
            </dt>
            <dd class="col-lg-8">
                @Html.DisplayFor(model => model.Output.Description)
            </dd>
        </dl>
        <dl class="row">
            <dt class="col-lg-4">
                @Html.DisplayNameFor(model => model.Output.StripeAccountId)
            </dt>
            <dd class="col-lg-8">
                @Html.DisplayFor(model => model.Output.StripeAccountId)
            </dd>
        </dl>
    </div>
    <div>
        <a asp-page="./Edit" asp-route-id="@Model.Output.Id">Edit</a> |
        <a asp-page="./Index">Back to List</a>
    </div>
</div>

Pages/Admin/Vendors/Edit.cshtml
@page "{id:int}"
@model EditModel

@{
    ViewData["Title"] = "Edit Vendor";
    ViewData["SelectedTab"] = "Vendors";
}

<div class="container">
    <h1>@ViewData["Title"]</h1>
    <hr />
    <div class="row">
        <div class="col-lg-6">
            <form method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Input.Id" />
                <div class="form-group">
                    <label asp-for="Input.Name" class="control-label"></label>
                    <input asp-for="Input.Name" class="form-control" />
                    <span asp-validation-for="Input.Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Input.Owner" class="control-label"></label>
                    <input asp-for="Input.Owner" class="form-control" />
                    <span asp-validation-for="Input.Owner" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Input.DessertType" class="control-label"></label>
                    <input asp-for="Input.DessertType" class="form-control" />
                    <span asp-validation-for="Input.DessertType" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Input.ImagePath" class="control-label"></label>
                    <input asp-for="Input.ImagePath" class="form-control" />
                    <span class="hint">Should be 300px by 150px</span>
                    <span asp-validation-for="Input.ImagePath" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Input.SocialMediaLink" class="control-label"></label>
                    <input asp-for="Input.SocialMediaLink" class="form-control" />
                    <span asp-validation-for="Input.SocialMediaLink" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Input.Description" class="control-label"></label>
                    <input asp-for="Input.Description" class="form-control" />
                    <span asp-validation-for="Input.Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Input.StripeAccountId" class="control-label"></label>
                    <input asp-for="Input.StripeAccountId" class="form-control" />
                    <span asp-validation-for="Input.StripeAccountId" class="text-danger"></span>
                </div>
                <input type="submit" value="Save" class="btn btn-primary" />
            </form>
        </div>
    </div>

    <div>
        <a asp-page="./Index">Back to List</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Admin/Vendors/Index.cshtml
@page
@model IndexModel

@{
    ViewData["Title"] = "Vendors";
    ViewData["SelectedTab"] = "Vendors";
}

<div class="container">
    <h1>@ViewData["Title"]</h1>
    <hr/>
    <div class="table-responsive">
        <table class="table">
            <thead class="thead-light">
                <tr>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.Vendors[0].Id)
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.Vendors[0].Name)
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.Vendors[0].DessertType)
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.Vendors[0].SocialMediaLink)
                    </th>
                    <th scope="col">
                        @Html.DisplayNameFor(model => model.Vendors[0].Description)
                    </th>
                    <th scope="col" class="col-action"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Vendors) 
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DessertType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SocialMediaLink)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td class="col-action">
                            <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                            <a class="confirm-dialog-trigger" asp-controller="Vendor" asp-action="Remove" asp-route-id="@item.Id" data-title="Confirm" data-body="Are you sure you want to remove this vendor?">Remove</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>